### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Guo-astro** [GaryB432/gb-nx#15]
Hi! Really useful one.Really naive question  I created a new command Just wondering how can run the command?Use nx serve  give me Error:No command specified.

<img width="795" alt="スクリーンショット 2023-04-27 11 12 46" src="https://user-images.githubusercontent.com/15899028/234742354-dfd9157a-d2e6-428e-ab65-e26fb656554f.png">
<img width="549" alt="スクリーンショット 2023-04-27 11 10 38" src="https://user-images.githubusercontent.com/15899028/234742087-644c22f4-44b4-4614-8877-08ea7c93636f.png">

**Comment by GaryB432** [comment]
### About `nx serve`

The `nx serve` command will run the application with no options or parameters resulting in the message `ERROR No command specified`. To use `nx serve`, temporarily edit your `main.ts` to bypass the argv parsing and run the command you want.

Of course, you want to revert such changes before building and distributing your multi-command CLI.

Alternatively, use a command like the following

```
nx build your-app;node dist/apps/your-app/main.js your-command your-parameter
```

If your CLI has only one command, consider using the plain [@nrwl/node:application generator](https://nx.dev/packages/node/generators/application)

**Comment by GaryB432** [comment]
closing this a resolved.  open a new issue if you have more trouble.
